# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'StarBoundNewZealand' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    fmt_target = installer.pods_project.targets.find { |target| target.name == 'fmt' }
    fmt_target&.build_configurations&.each do |build_configuration|
      build_configuration.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
    end

    fmt_base_header = File.join(installer.sandbox.root, 'fmt/include/fmt/base.h')
    if File.exist?(fmt_base_header)
      contents = File.read(fmt_base_header)
      consteval_patch = "#undef FMT_USE_CONSTEVAL\n#  define FMT_USE_CONSTEVAL 0\n"
      unless contents.include?(consteval_patch)
        patched_contents = contents.sub(
          "#endif\n#if FMT_USE_CONSTEVAL",
          "#endif\n#{consteval_patch}#if FMT_USE_CONSTEVAL"
        )
        if patched_contents != contents
          File.chmod(0o644, fmt_base_header)
          File.write(fmt_base_header, patched_contents)
        end
      end
    end
  end
end
